services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:5002/api
      - NODE_ENV=development
    restart: always
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5002:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=safevideo
      - DB_USER=safevideo_user
      - DB_PASSWORD=your_strong_password
      - JWT_SECRET=your_secure_jwt_secret_key
      - PORT=5000
      - NODE_ENV=development
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_strong_password
      - MYSQL_DATABASE=safevideo
      - MYSQL_USER=safevideo_user
      - MYSQL_PASSWORD=your_strong_password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_strong_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local
