global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'safevideo-production'
    environment: 'prod'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # SafeVideo application servers
  - job_name: 'safevideo-blue'
    static_configs:
      - targets: ['server-blue:5000']
    metrics_path: /metrics
    scrape_interval: 15s
    params:
      environment: ['blue']

  - job_name: 'safevideo-green'
    static_configs:
      - targets: ['server-green:5000']
    metrics_path: /metrics
    scrape_interval: 15s
    params:
      environment: ['green']

  # HAProxy load balancer
  - job_name: 'haproxy'
    static_configs:
      - targets: ['load-balancer:8404']
    metrics_path: /stats/prometheus
    scrape_interval: 30s

  # MySQL database
  - job_name: 'mysql-master'
    static_configs:
      - targets: ['mysql-master:9104']
    scrape_interval: 30s

  - job_name: 'mysql-replica'
    static_configs:
      - targets: ['mysql-replica:9104']
    scrape_interval: 30s

  # Redis cluster
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cluster:9121']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

  # Nginx reverse proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'safevideo-custom'
    static_configs:
      - targets: ['server-blue:5000', 'server-green:5000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    basic_auth:
      username: 'metrics'
      password: 'secure_metrics_password'

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"
